---
title: Maak je eigen aangepaste kleurenpalet
hero_image: images/banner.png
description: Maak je eigen aangepaste kleurenpalet.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Maak je eigen aangepaste kleurenpalet
