title: Crea tu propia paleta de colores personalizada
hero_image: images/banner.png
description: Crea tu propia paleta de colores personalizada.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Crea tu propia paleta de colores personalizada
