title: Create your own custom colour palette
hero_image: images/banner.png
description: Create your own custom colour palette.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Create your own custom colour palette
